<template>
<!--    <div>分类</div>-->
    <div class="wrapper">
        <ul class="content">
            <li>列表1</li>
            <li>列表2</li>
            <li>列表3</li>
            <li>列表4</li>
            <li>列表5</li>
            <li>列表6</li>
            <li>列表7</li>
            <li>列表8</li>
            <li>列表9</li>
            <li>列表10</li>
            <li>列表11</li>
            <li>列表12</li>
            <li>列表13</li>
            <li>列表14</li>
            <li>列表15</li>
            <li>列表16</li>
            <li>列表17</li>
            <li>列表18</li>
            <li>列表19</li>
            <li>列表20</li>
            <li>列表21</li>
            <li>列表22</li>
            <li>列表23</li>
            <li>列表24</li>
            <li>列表25</li>
            <li>列表26</li>
            <li>列表27</li>
            <li>列表28</li>
            <li>列表29</li>
            <li>列表30</li>
            <li>列表31</li>
            <li>列表32</li>
            <li>列表33</li>
            <li>列表34</li>
            <li>列表35</li>
            <li>列表36</li>
            <li>列表37</li>
            <li>列表38</li>
            <li>列表39</li>
            <li>列表40</li>
            <li>列表41</li>
            <li>列表42</li>
            <li>列表43</li>
            <li>列表44</li>
            <li>列表45</li>
            <li>列表46</li>
            <li>列表47</li>
            <li>列表48</li>
            <li>列表49</li>
            <li>列表50</li>
            <li>列表51</li>
            <li>列表52</li>
            <li>列表53</li>
            <li>列表54</li>
            <li>列表55</li>
            <li>列表56</li>
            <li>列表57</li>
            <li>列表58</li>
            <li>列表59</li>
            <li>列表60</li>
            <li>列表61</li>
            <li>列表62</li>
            <li>列表63</li>
            <li>列表64</li>
            <li>列表65</li>
            <li>列表66</li>
            <li>列表67</li>
            <li>列表68</li>
            <li>列表69</li>
            <li>列表70</li>
            <li>列表71</li>
            <li>列表72</li>
            <li>列表73</li>
            <li>列表74</li>
            <li>列表75</li>
            <li>列表76</li>
            <li>列表77</li>
            <li>列表78</li>
            <li>列表79</li>
            <li>列表80</li>
            <li>列表81</li>
            <li>列表82</li>
            <li>列表83</li>
            <li>列表84</li>
            <li>列表85</li>
            <li>列表86</li>
            <li>列表87</li>
            <li>列表88</li>
            <li>列表89</li>
            <li>列表90</li>
            <li>列表91</li>
            <li>列表92</li>
            <li>列表93</li>
            <li>列表94</li>
            <li>列表95</li>
            <li>列表96</li>
            <li>列表97</li>
            <li>列表98</li>
            <li>列表99</li>
            <li>列表100</li>
            <li>列表101</li>
            <li>列表102</li>
            <li>列表103</li>
            <li>列表104</li>
            <li>列表105</li>
            <li>列表106</li>
            <li>列表107</li>
            <li>列表108</li>
            <li>列表109</li>
            <li>列表110</li>
            <li>列表111</li>
            <li>列表112</li>
            <li>列表113</li>
            <li>列表114</li>
            <li>列表115</li>
            <li>列表116</li>
            <li>列表117</li>
            <li>列表118</li>
            <li>列表119</li>
            <li>列表120</li>
            <li>列表121</li>
            <li>列表122</li>
            <li>列表123</li>
            <li>列表124</li>
            <li>列表125</li>
            <li>列表126</li>
            <li>列表127</li>
            <li>列表128</li>
            <li>列表129</li>
            <li>列表130</li>
            <li>列表131</li>
            <li>列表132</li>
            <li>列表133</li>
            <li>列表134</li>
            <li>列表135</li>
            <li>列表136</li>
            <li>列表137</li>
            <li>列表138</li>
            <li>列表139</li>
            <li>列表140</li>
            <li>列表141</li>
            <li>列表142</li>
            <li>列表143</li>
            <li>列表144</li>
            <li>列表145</li>
            <li>列表146</li>
            <li>列表147</li>
            <li>列表148</li>
            <li>列表149</li>
            <li>列表150</li>
            <li>列表151</li>
            <li>列表152</li>
            <li>列表153</li>
            <li>列表154</li>
            <li>列表155</li>
            <li>列表156</li>
            <li>列表157</li>
            <li>列表158</li>
            <li>列表159</li>
            <li>列表160</li>
            <li>列表161</li>
            <li>列表162</li>
            <li>列表163</li>
            <li>列表164</li>
            <li>列表165</li>
            <li>列表166</li>
            <li>列表167</li>
            <li>列表168</li>
            <li>列表169</li>
            <li>列表170</li>
            <li>列表171</li>
            <li>列表172</li>
            <li>列表173</li>
            <li>列表174</li>
            <li>列表175</li>
            <li>列表176</li>
            <li>列表177</li>
            <li>列表178</li>
            <li>列表179</li>
            <li>列表180</li>
            <li>列表181</li>
            <li>列表182</li>
            <li>列表183</li>
            <li>列表184</li>
            <li>列表185</li>
            <li>列表186</li>
            <li>列表187</li>
            <li>列表188</li>
            <li>列表189</li>
            <li>列表190</li>
            <li>列表191</li>
            <li>列表192</li>
            <li>列表193</li>
            <li>列表194</li>
            <li>列表195</li>
            <li>列表196</li>
            <li>列表197</li>
            <li>列表198</li>
            <li>列表199</li>
            <li>列表200</li>
            <li>列表201</li>
            <li>列表202</li>
            <li>列表203</li>
            <li>列表204</li>
            <li>列表205</li>
            <li>列表206</li>
            <li>列表207</li>
            <li>列表208</li>
            <li>列表209</li>
            <li>列表210</li>
            <li>列表211</li>
            <li>列表212</li>
            <li>列表213</li>
            <li>列表214</li>
            <li>列表215</li>
            <li>列表216</li>
            <li>列表217</li>
            <li>列表218</li>
            <li>列表219</li>
            <li>列表220</li>
            <li>列表221</li>
            <li>列表222</li>
            <li>列表223</li>
            <li>列表224</li>
            <li>列表225</li>
            <li>列表226</li>
            <li>列表227</li>
            <li>列表228</li>
            <li>列表229</li>
            <li>列表230</li>
            <li>列表231</li>
            <li>列表232</li>
            <li>列表233</li>
            <li>列表234</li>
            <li>列表235</li>
            <li>列表236</li>
            <li>列表237</li>
            <li>列表238</li>
            <li>列表239</li>
            <li>列表240</li>
            <li>列表241</li>
            <li>列表242</li>
            <li>列表243</li>
            <li>列表244</li>
            <li>列表245</li>
            <li>列表246</li>
            <li>列表247</li>
            <li>列表248</li>
            <li>列表249</li>
            <li>列表250</li>
            <li>列表251</li>
            <li>列表252</li>
            <li>列表253</li>
            <li>列表254</li>
            <li>列表255</li>
            <li>列表256</li>
            <li>列表257</li>
            <li>列表258</li>
            <li>列表259</li>
            <li>列表260</li>
            <li>列表261</li>
            <li>列表262</li>
            <li>列表263</li>
            <li>列表264</li>
            <li>列表265</li>
            <li>列表266</li>
            <li>列表267</li>
            <li>列表268</li>
            <li>列表269</li>
            <li>列表270</li>
            <li>列表271</li>
            <li>列表272</li>
            <li>列表273</li>
            <li>列表274</li>
            <li>列表275</li>
            <li>列表276</li>
            <li>列表277</li>
            <li>列表278</li>
            <li>列表279</li>
            <li>列表280</li>
            <li>列表281</li>
            <li>列表282</li>
            <li>列表283</li>
            <li>列表284</li>
            <li>列表285</li>
            <li>列表286</li>
            <li>列表287</li>
            <li>列表288</li>
            <li>列表289</li>
            <li>列表290</li>
            <li>列表291</li>
            <li>列表292</li>
            <li>列表293</li>
            <li>列表294</li>
            <li>列表295</li>
            <li>列表296</li>
            <li>列表297</li>
            <li>列表298</li>
            <li>列表299</li>
            <li>列表300</li>
            <li>列表301</li>
            <li>列表302</li>
            <li>列表303</li>
            <li>列表304</li>
            <li>列表305</li>
            <li>列表306</li>
            <li>列表307</li>
            <li>列表308</li>
            <li>列表309</li>
            <li>列表310</li>
            <li>列表311</li>
            <li>列表312</li>
            <li>列表313</li>
            <li>列表314</li>
            <li>列表315</li>
            <li>列表316</li>
            <li>列表317</li>
            <li>列表318</li>
            <li>列表319</li>
            <li>列表320</li>
            <li>列表321</li>
            <li>列表322</li>
            <li>列表323</li>
            <li>列表324</li>
            <li>列表325</li>
            <li>列表326</li>
            <li>列表327</li>
            <li>列表328</li>
            <li>列表329</li>
            <li>列表330</li>
            <li>列表331</li>
            <li>列表332</li>
            <li>列表333</li>
            <li>列表334</li>
            <li>列表335</li>
            <li>列表336</li>
            <li>列表337</li>
            <li>列表338</li>
            <li>列表339</li>
            <li>列表340</li>
            <li>列表341</li>
            <li>列表342</li>
            <li>列表343</li>
            <li>列表344</li>
            <li>列表345</li>
            <li>列表346</li>
            <li>列表347</li>
            <li>列表348</li>
            <li>列表349</li>
            <li>列表350</li>
            <li>列表351</li>
            <li>列表352</li>
            <li>列表353</li>
            <li>列表354</li>
            <li>列表355</li>
            <li>列表356</li>
            <li>列表357</li>
            <li>列表358</li>
            <li>列表359</li>
            <li>列表360</li>
            <li>列表361</li>
            <li>列表362</li>
            <li>列表363</li>
            <li>列表364</li>
            <li>列表365</li>
            <li>列表366</li>
            <li>列表367</li>
            <li>列表368</li>
            <li>列表369</li>
            <li>列表370</li>
            <li>列表371</li>
            <li>列表372</li>
            <li>列表373</li>
            <li>列表374</li>
            <li>列表375</li>
            <li>列表376</li>
            <li>列表377</li>
            <li>列表378</li>
            <li>列表379</li>
            <li>列表380</li>
            <li>列表381</li>
            <li>列表382</li>
            <li>列表383</li>
            <li>列表384</li>
            <li>列表385</li>
            <li>列表386</li>
            <li>列表387</li>
            <li>列表388</li>
            <li>列表389</li>
            <li>列表390</li>
            <li>列表391</li>
            <li>列表392</li>
            <li>列表393</li>
            <li>列表394</li>
            <li>列表395</li>
            <li>列表396</li>
            <li>列表397</li>
            <li>列表398</li>
            <li>列表399</li>
            <li>列表400</li>
            <li>列表401</li>
            <li>列表402</li>
            <li>列表403</li>
            <li>列表404</li>
            <li>列表405</li>
            <li>列表406</li>
            <li>列表407</li>
            <li>列表408</li>
            <li>列表409</li>
            <li>列表410</li>
            <li>列表411</li>
            <li>列表412</li>
            <li>列表413</li>
            <li>列表414</li>
            <li>列表415</li>
            <li>列表416</li>
            <li>列表417</li>
            <li>列表418</li>
            <li>列表419</li>
            <li>列表420</li>
            <li>列表421</li>
            <li>列表422</li>
            <li>列表423</li>
            <li>列表424</li>
            <li>列表425</li>
            <li>列表426</li>
            <li>列表427</li>
            <li>列表428</li>
            <li>列表429</li>
            <li>列表430</li>
            <li>列表431</li>
            <li>列表432</li>
            <li>列表433</li>
            <li>列表434</li>
            <li>列表435</li>
            <li>列表436</li>
            <li>列表437</li>
            <li>列表438</li>
            <li>列表439</li>
            <li>列表440</li>
            <li>列表441</li>
            <li>列表442</li>
            <li>列表443</li>
            <li>列表444</li>
            <li>列表445</li>
            <li>列表446</li>
            <li>列表447</li>
            <li>列表448</li>
            <li>列表449</li>
            <li>列表450</li>
            <li>列表451</li>
            <li>列表452</li>
            <li>列表453</li>
            <li>列表454</li>
            <li>列表455</li>
            <li>列表456</li>
            <li>列表457</li>
            <li>列表458</li>
            <li>列表459</li>
            <li>列表460</li>
            <li>列表461</li>
            <li>列表462</li>
            <li>列表463</li>
            <li>列表464</li>
            <li>列表465</li>
            <li>列表466</li>
            <li>列表467</li>
            <li>列表468</li>
            <li>列表469</li>
            <li>列表470</li>
            <li>列表471</li>
            <li>列表472</li>
            <li>列表473</li>
            <li>列表474</li>
            <li>列表475</li>
            <li>列表476</li>
            <li>列表477</li>
            <li>列表478</li>
            <li>列表479</li>
            <li>列表480</li>
            <li>列表481</li>
            <li>列表482</li>
            <li>列表483</li>
            <li>列表484</li>
            <li>列表485</li>
            <li>列表486</li>
            <li>列表487</li>
            <li>列表488</li>
            <li>列表489</li>
            <li>列表490</li>
            <li>列表491</li>
            <li>列表492</li>
            <li>列表493</li>
            <li>列表494</li>
            <li>列表495</li>
            <li>列表496</li>
            <li>列表497</li>
            <li>列表498</li>
            <li>列表499</li>
            <li>列表500</li>
        </ul>
    </div>
</template>

<script>
    import BScroll from 'better-scroll'
    export default {
        name: "Category",
        data(){
            return{
                scroll:null
            }
        },
        mounted() {
            this.scroll = new BScroll(document.querySelector('.wrapper'),{
                //所有的滚动都可以监听
                probeType:3,
                //上拉加载更多
                pullUpLoad:true
            })
            this.scroll.on('scroll',(position => {
                console.log(position);
            }))
            this.scroll.on('pullingUp',()=>{
                console.log('上拉加载更多');
            })
        },
        methods:{

        }
    }
</script>

<style scoped>
.wrapper{
    height: 150px;
    background-color: red;
    overflow: hidden;
}
</style>